/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JPanel;

/**
 *
 * @author Fu
 */
public class Card extends javax.swing.JPanel {

    /**
     * Creates new form CardLayout
     */
    public Card() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listDriver1 = new view.ListDriver();
        adminDashboard1 = new view.AdminDashboard();
        loginAdmin1 = new view.LoginAdmin();

        setLayout(new java.awt.CardLayout());
        add(adminDashboard1, "card2");
        add(loginAdmin1, "card4");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.AdminDashboard adminDashboard1;
    private view.ListDriver listDriver1;
    private view.LoginAdmin loginAdmin1;
    // End of variables declaration//GEN-END:variables

    public void show(JPanel mainPanel, String home) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
